<a href="https://colab.research.google.com/github/Dubeyrock/Get-Started-with-Numpy/blob/main/Getting_started_with_Numpy_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
! pip install numpy

In [2]:
import numpy as np

In [3]:
np

<module 'numpy' from '/usr/local/lib/python3.10/dist-packages/numpy/__init__.py'>

In [4]:
lst =[1,5,6]

In [5]:
type(lst)

list

In [6]:
arr = np.array(lst)

In [7]:
arr

array([1, 5, 6])

In [8]:
type(arr)

numpy.ndarray

In [12]:
import numpy as np

# Create a NumPy array for demonstration
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Get the number of dimensions
num_dimensions = arr.ndim

# Print the number of dimensions
print("Number of dimensions:", num_dimensions)


Number of dimensions: 2


In [13]:
arr.ndim

2

In [14]:
arr.shape

(2, 3)

In [15]:
arr.size

6

In [16]:
arr.dtype

dtype('int64')

In [20]:
np.zeros = np.zeros((3,5))

In [22]:
import numpy as np

zeros = np.zeros((3, 5))

print(zeros)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [23]:
ones = np.ones((6,8))

In [24]:
ones

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

Reshape and Random Number Generator

In [25]:
import numpy as np

In [26]:
np.random.random((3,3))

array([[0.11243489, 0.18211982, 0.0357582 ],
       [0.99550492, 0.52014732, 0.82495231],
       [0.80978037, 0.76606401, 0.77608561]])

In [27]:
np.random.random((3,3))

array([[0.93145476, 0.29595108, 0.85351513],
       [0.28003738, 0.92473162, 0.22079262],
       [0.10283949, 0.79139398, 0.66288511]])

In [28]:
if np.random.random() > 0.5:
  print("Run the function")
else:
  print("Don't run the function ")


Don't run the function 


In [29]:
np.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [31]:
np.linspace(1,7,10)

array([1.        , 1.66666667, 2.33333333, 3.        , 3.66666667,
       4.33333333, 5.        , 5.66666667, 6.33333333, 7.        ])

In [34]:
arr = np.random.random((4,3))
arr

array([[0.98502697, 0.36895527, 0.51141099],
       [0.74081599, 0.24685389, 0.6615342 ],
       [0.24043535, 0.29418725, 0.15746477],
       [0.97531813, 0.61469407, 0.40573485]])

In [35]:
np.reshape(arr, (3,4))

array([[0.98502697, 0.36895527, 0.51141099, 0.74081599],
       [0.24685389, 0.6615342 , 0.24043535, 0.29418725],
       [0.15746477, 0.97531813, 0.61469407, 0.40573485]])

In [36]:
arr

array([[0.98502697, 0.36895527, 0.51141099],
       [0.74081599, 0.24685389, 0.6615342 ],
       [0.24043535, 0.29418725, 0.15746477],
       [0.97531813, 0.61469407, 0.40573485]])

In [38]:
arr = np.reshape(arr , (6,2))
arr

array([[0.98502697, 0.36895527],
       [0.51141099, 0.74081599],
       [0.24685389, 0.6615342 ],
       [0.24043535, 0.29418725],
       [0.15746477, 0.97531813],
       [0.61469407, 0.40573485]])

In [39]:
arr.flatten()

array([0.98502697, 0.36895527, 0.51141099, 0.74081599, 0.24685389,
       0.6615342 , 0.24043535, 0.29418725, 0.15746477, 0.97531813,
       0.61469407, 0.40573485])

Arithmetic Operations on Array

In [40]:
import numpy as np

In [41]:
arr = np.array([1,3, 4, 5, 7, 8])

In [42]:
arr

array([1, 3, 4, 5, 7, 8])

In [43]:
arr + 1

array([2, 4, 5, 6, 8, 9])

In [44]:
arr * 5

array([ 5, 15, 20, 25, 35, 40])

In [45]:
print(arr+1)
print(arr-1)
print(arr*1)
print(arr/1)
print(arr % 1)


[2 4 5 6 8 9]
[0 2 3 4 6 7]
[1 3 4 5 7 8]
[1. 3. 4. 5. 7. 8.]
[0 0 0 0 0 0]


In [46]:
arr

array([1, 3, 4, 5, 7, 8])

In [47]:
arr = arr + 1

In [48]:
arr

array([2, 4, 5, 6, 8, 9])

In [49]:
arr += 1

In [50]:
arr

array([ 3,  5,  6,  7,  9, 10])

In [52]:
arr =+ 1
arr

1

In [53]:
arr*=2

In [54]:
arr

2

Arithmetic Operations on Multiple Arrays

In [55]:
import numpy as np

In [56]:
arr1 = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])

arr2 = np.array([[9,8,7],
               [6,5,4],
               [3,2,1]])

arr3 = np.array([[9,8,7,5],
               [6,5,4,2],
               [3,2,1,5]])


In [57]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
arr2

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [59]:
arr1 + arr2

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [60]:
arr2*arr1

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

In [61]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
arr2

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [63]:
(1*9) + (2*6) + (3*3)

30

In [64]:
arr1.dot(arr2)

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [65]:
arr2.dot(arr1)

array([[ 90, 114, 138],
       [ 54,  69,  84],
       [ 18,  24,  30]])

In [66]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:

arr = np.array([1,2,3,4,5])

In [69]:
arr[:-2]

array([1, 2, 3])

In [70]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [71]:
arr1[ 1: , 1 : ]

array([[5, 6],
       [8, 9]])

Array Sorting

In [72]:

arr = np.array([[7,3,8,6,4], [7,2,9,8,6],[5,4,2,3,1]])
arr

array([[7, 3, 8, 6, 4],
       [7, 2, 9, 8, 6],
       [5, 4, 2, 3, 1]])

In [73]:
np.sort(arr , axis = 1, kind = 'mergesort')

array([[3, 4, 6, 7, 8],
       [2, 6, 7, 8, 9],
       [1, 2, 3, 4, 5]])

In [74]:
np.sort(arr , axis = 0, kind = 'mergesort')


array([[5, 2, 2, 3, 1],
       [7, 3, 8, 6, 4],
       [7, 4, 9, 8, 6]])

In [75]:
np.sort(arr , kind = 'mergesort')


array([[3, 4, 6, 7, 8],
       [2, 6, 7, 8, 9],
       [1, 2, 3, 4, 5]])

Array Merging

In [76]:
arr1 = np.array([[1,2,3,4], [5,6,7,8]])
arr2 = np.array([[8,7,6,5], [4,3,2,1]])


In [77]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [78]:
arr2

array([[8, 7, 6, 5],
       [4, 3, 2, 1]])

In [79]:

np.vstack((arr1,arr2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [80]:

np.hstack((arr1,arr2))


array([[1, 2, 3, 4, 8, 7, 6, 5],
       [5, 6, 7, 8, 4, 3, 2, 1]])

In [81]:
np.hstack((arr2,arr1))

array([[8, 7, 6, 5, 1, 2, 3, 4],
       [4, 3, 2, 1, 5, 6, 7, 8]])

In [82]:
arr = np.concatenate((arr1,arr2), axis = 0)


In [83]:
np.concatenate((arr1,arr2), axis = 1)


array([[1, 2, 3, 4, 8, 7, 6, 5],
       [5, 6, 7, 8, 4, 3, 2, 1]])

In [84]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [85]:
np.hsplit(arr, 2)

[array([[1, 2],
        [5, 6],
        [8, 7],
        [4, 3]]),
 array([[3, 4],
        [7, 8],
        [6, 5],
        [2, 1]])]

In [86]:
np.vsplit(arr, 2)


[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[8, 7, 6, 5],
        [4, 3, 2, 1]])]

Array Slicing - DAP

In [87]:

arr = np.array([1,2,3,4,5,6,7,8])

In [88]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [89]:
arr[3: ]

array([4, 5, 6, 7, 8])

In [90]:
arr[ : -3]


array([1, 2, 3, 4, 5])

In [91]:
arr[3  :  -3]


array([4, 5])

In [92]:

arr = np.array([[1,2,3,4],[5,6,7,8],[8,7,6,5],[4,3,2,1]])

In [93]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [94]:
arr[ 3 , 1]

3

In [95]:
arr[ 1: , 1:]


array([[6, 7, 8],
       [7, 6, 5],
       [3, 2, 1]])

Automating using Numpy

In [96]:
lst = [1,2,3,4,5,6,7,8,9,10]

In [97]:

q = 0

for i in lst:
  if (i > 5):
    print(i)
    q += 1

print(q)

6
7
8
9
10
5


In [99]:
lst = np.array([1,2,3,4,5,6,7,8,9,10])


In [100]:
print(len(lst[lst > 5]))
print(lst[lst>5])



5
[ 6  7  8  9 10]


In [101]:

print(len(lst[lst % 3 == 0]))
print(lst[lst % 3 == 0])


3
[3 6 9]
